#!/usr/bin/env python3
# Copyright 2026 Alibaba Group.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""SOL-ExecBench correctness + benchmark harness for a kernel-opt workspace.

This is the IMMUTABLE ground-truth harness. It runs the *real* SOL-ExecBench
evaluator (`sol-execbench`) against this workspace's `solution.json` over EVERY
workload in `workload.jsonl`, using SOL's own input generation and per-workload
tolerances. A PASS here == a directly submittable solution (identical evaluator).

`solution.json` lists `kernel.py` as a source WITHOUT inline content, so the
evaluator reads the live `kernel.py` from disk each run — `kernel.py` is the
single source of truth. Optimization iterations edit `kernel.py` only (and
`solution.json` itself only when languages / dependencies / entry_point change).

OPTIMIZATION GOAL = minimize the GEOMEAN of per-workload kernel latency
(recorded as `performance.latency_us`). The harness also records the arithmetic
mean, the per-workload latency (`performance.latency_us_by_shape`, keyed by the
workload `uuid`), and the geomean speedup vs the reference.

DO NOT edit this file to change the benchmark methodology (see reference/CLAUDE.md
"Benchmark Harness Integrity"). Cross-version comparison depends on it being fixed.

Usage (run with cwd = the workspace):
    python test_kernel.py                 # record into the latest memory/v<N>.json (or v0)
    python test_kernel.py --version v3    # record into memory/v3.json
    python test_kernel.py --no-memory     # just run + print; do not touch memory/
"""

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path


def _sol_execbench_cmd() -> list[str]:
    """Locate the SOL-ExecBench CLI. Prefer the console script; fall back to `uv run`."""
    exe = shutil.which("sol-execbench")
    if exe:
        return [exe]
    if shutil.which("uv"):
        return ["uv", "run", "sol-execbench"]
    raise SystemExit(
        "sol-execbench CLI not found on PATH. Install SOL-ExecBench "
        "(`uv pip install -e <SOL-ExecBench>`) or expose the console script."
    )


def _geomean(xs: list[float]) -> float:
    xs = [x for x in xs if x and x > 0]
    if not xs:
        return 0.0
    return math.exp(sum(math.log(x) for x in xs) / len(xs))


def _run_eval(workspace: Path, traces_path: Path) -> None:
    eval_workspace = workspace
    temp_workspace: tempfile.TemporaryDirectory[str] | None = None
    definition_path = workspace / "definition.json"
    if definition_path.is_file():
        definition = json.loads(definition_path.read_text(encoding="utf-8"))
        # The published FlashInfer-Bench definitions use an empty provenance ID,
        # while recent SOL-ExecBench models accept either a non-empty string or
        # null.  Match the gateway's SOL compatibility patch in an ephemeral copy;
        # the campaign's immutable definition.json remains byte-for-byte intact.
        if definition.get("hf_id") == "":
            temp_workspace = tempfile.TemporaryDirectory(prefix="sol-eval-")
            eval_workspace = Path(temp_workspace.name) / "workspace"
            shutil.copytree(workspace, eval_workspace)
            definition["hf_id"] = None
            (eval_workspace / "definition.json").write_text(
                json.dumps(definition, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            print("[test_kernel] applying ephemeral hf_id compatibility patch", flush=True)

    try:
        cmd = _sol_execbench_cmd() + [".", "--solution", "solution.json", "-o", str(traces_path)]
        if (eval_workspace / "config.json").exists():
            cmd += ["--config", "config.json"]
        # Allow overriding the evaluator subprocess timeout via env var (seconds).
        # The PyTorch V0 reference can be very slow on large workloads; default 1200s.
        eval_timeout = os.environ.get("SOL_EVAL_TIMEOUT", "1200")
        cmd += ["--timeout", str(eval_timeout)]
        print(f"[test_kernel] {' '.join(cmd)}", flush=True)
        # Stream the evaluator's own table to stderr; traces go to the JSONL file.
        subprocess.run(cmd, cwd=str(eval_workspace), check=False)
    finally:
        if temp_workspace is not None:
            temp_workspace.cleanup()


def _parse_traces(traces_path: Path) -> list[dict]:
    if not traces_path.exists():
        raise SystemExit(f"[test_kernel] evaluator produced no traces at {traces_path}")
    return [json.loads(line) for line in traces_path.read_text().splitlines() if line.strip()]


def _summarize(traces: list[dict]) -> dict:
    """Reduce raw SOL traces to the metrics we record. Latencies converted ms -> us."""
    total = len(traces)
    per_shape: dict[str, float] = {}      # uuid -> latency_us
    lat_us: list[float] = []
    speedups: list[float] = []
    max_abs = 0.0
    max_rel = 0.0
    failures: list[str] = []

    for t in traces:
        ev = t.get("evaluation") or {}
        wl = t.get("workload") or {}
        uuid = wl.get("uuid") or "?"
        status = ev.get("status")
        corr = ev.get("correctness") or {}
        if isinstance(corr.get("max_absolute_error"), (int, float)):
            max_abs = max(max_abs, float(corr["max_absolute_error"]))
        if isinstance(corr.get("max_relative_error"), (int, float)):
            max_rel = max(max_rel, float(corr["max_relative_error"]))
        if status == "PASSED":
            perf = ev.get("performance") or {}
            us = float(perf.get("latency_ms") or 0.0) * 1000.0
            per_shape[uuid] = us
            if us > 0:
                lat_us.append(us)
            spd = perf.get("speedup_factor")
            if isinstance(spd, (int, float)) and spd > 0:
                speedups.append(float(spd))
        else:
            failures.append(f"{uuid[:8]}={status or 'NO_EVAL'} ({wl.get('axes')})")

    passed = total - len(failures)
    all_pass = total > 0 and passed == total
    return {
        "total": total,
        "passed": passed,
        "all_pass": all_pass,
        "failures": failures,
        "latency_us_by_shape": per_shape,
        "latency_us_geomean": _geomean(lat_us),
        "latency_us_arith_mean": (sum(lat_us) / len(lat_us)) if lat_us else 0.0,
        "speedup_vs_ref_geomean": _geomean(speedups),
        "max_abs_err": max_abs,
        "max_rel_err": max_rel,
    }


def _infer_version(workspace: Path) -> str:
    """Largest STRICT integer version present as memory/v<N>.json.

    Accepts only stems matching ^v\\d+\\.json$ exactly — experimental files
    like v71_512.json (scratch variants of v71) MUST NOT be misread as v71512
    (Python's PEP 515 underscores-in-numeric-literals trap).
    """
    import re
    _STRICT = re.compile(r"^v(\d+)\.json$")
    mem = workspace / "memory"
    best = 0
    if mem.exists():
        for p in mem.glob("v*.json"):
            m = _STRICT.match(p.name)
            if m is not None:
                best = max(best, int(m.group(1)))
    return f"v{best}"


def _record_memory(workspace: Path, version: str, s: dict) -> Path:
    """Merge harness-owned fields into memory/v<N>.json (create if missing)."""
    mem_dir = workspace / "memory"
    mem_dir.mkdir(parents=True, exist_ok=True)
    path = mem_dir / f"{version}.json"
    mem = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}

    mem.setdefault("version", version)
    mem.setdefault("masked", False)
    mem["timestamp"] = datetime.now(timezone.utc).isoformat()

    perf = mem.setdefault("performance", {})
    # GOAL metric: latency_us == geomean of per-workload latency.
    perf["latency_us"] = s["latency_us_geomean"]
    perf["latency_us_geomean"] = s["latency_us_geomean"]
    perf["latency_us_arith_mean"] = s["latency_us_arith_mean"]
    perf["latency_us_by_shape"] = s["latency_us_by_shape"]
    perf["speedup_vs_ref_geomean"] = s["speedup_vs_ref_geomean"]

    corr = mem.setdefault("correctness", {})
    corr["status"] = "PASS" if s["all_pass"] else "FAIL"
    corr["max_abs_err"] = s["max_abs_err"]
    corr["max_rel_err"] = s["max_rel_err"]

    gate = mem.setdefault("quality_gate", {})
    gate["result"] = "PASS" if s["all_pass"] else "FAIL"
    gate["failure_reason"] = None if s["all_pass"] else "; ".join(s["failures"])[:2000]

    path.write_text(json.dumps(mem, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def _write_submission(workspace: Path) -> "Path | None":
    """Emit the self-contained, directly-submittable SOL solution next to the kernel.

    Inlines each source's content from disk into `solution.json` → `submission.json`.
    Called only after a PASS, so every passing version leaves a ready-to-submit artifact
    that requires no separate finalize/re-validation step (the PASS already validated it).
    """
    sol_path = workspace / "solution.json"
    if not sol_path.exists():
        return None
    sol = json.loads(sol_path.read_text(encoding="utf-8"))
    for src in sol.get("sources", []):
        p = workspace / src["path"]
        if p.is_file():
            src["content"] = p.read_text(encoding="utf-8")
    out = workspace / "submission.json"
    out.write_text(json.dumps(sol, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="SOL-ExecBench correctness+bench harness.")
    ap.add_argument("--workspace", default=".", help="Workspace dir (default: cwd).")
    ap.add_argument("--version", default=None, help="memory version to record, e.g. v3 (default: latest / v0).")
    ap.add_argument("--no-memory", action="store_true", help="Run + print only; do not write memory/.")
    ap.add_argument("--seed", type=int, default=None,
                    help="Random seed for input generation. If not set, uses sol-execbench default.")
    ap.add_argument("--multi-seed", type=int, default=0, metavar="N",
                    help="Run N additional seeds (1..N) for robustness check. Reports PASS only if ALL seeds pass.")
    args = ap.parse_args(argv)

    workspace = Path(args.workspace).resolve()
    if not (workspace / "solution.json").exists():
        raise SystemExit(f"[test_kernel] no solution.json in {workspace}")

    # Set seed if provided (before any eval calls)
    if args.seed is not None:
        import torch as _torch_seed
        _torch_seed.manual_seed(args.seed)
        import random as _rnd_seed
        _rnd_seed.seed(args.seed)
        try:
            import numpy as _np_seed
            _np_seed.random.seed(args.seed)
        except ImportError:
            pass

    traces_path = workspace / "traces.jsonl"
    _run_eval(workspace, traces_path)
    s = _summarize(_parse_traces(traces_path))

    print("\n[test_kernel] ── SOL-ExecBench result ─────────────────────────────")
    if args.seed is not None:
        print(f"  SEED                     : {args.seed}")
    print(f"  workloads PASSED         : {s['passed']}/{s['total']}")
    print(f"  GEOMEAN kernel latency   : {s['latency_us_geomean']:.1f} us   <-- OPTIMIZATION GOAL (minimize)")
    print(f"  arith-mean kernel latency: {s['latency_us_arith_mean']:.1f} us")
    print(f"  geomean speedup vs ref   : {s['speedup_vs_ref_geomean']:.3f}x")
    print(f"  worst abs / rel error    : {s['max_abs_err']:.2e} / {s['max_rel_err']:.2e}")
    if s["failures"]:
        print(f"  FAILURES                 : {'; '.join(s['failures'])}")
    print("  ────────────────────────────────────────────────────────────────")

    # Multi-seed robustness check.
    #
    # The production evaluator uses freshly-randomized inputs every call; a kernel
    # that passes on a single seed/smoke run can still fail correctness on a
    # different draw (e.g. numerical edge-cases that only manifest at certain
    # magnitudes). Re-running the evaluator N times under different seeds gives
    # cheap confidence that the kernel is robust, not just lucky.
    if args.multi_seed > 0:
        print(f"\n[test_kernel] ── Multi-seed robustness ({args.multi_seed} seeds) ──")
        all_seeds_pass = s["all_pass"]
        worst_abs_all = s["max_abs_err"]
        worst_rel_all = s["max_rel_err"]
        for seed_i in range(1, args.multi_seed + 1):
            import torch as _torch_ms
            _torch_ms.manual_seed(seed_i * 1000 + 42)
            import random as _rnd_ms
            _rnd_ms.seed(seed_i * 1000 + 42)
            try:
                import numpy as _np_ms
                _np_ms.random.seed(seed_i * 1000 + 42)
            except ImportError:
                pass
            traces_seed = workspace / f"traces_seed{seed_i}.jsonl"
            _run_eval(workspace, traces_seed)
            ss = _summarize(_parse_traces(traces_seed))
            tag = "PASS" if ss["all_pass"] else "FAIL"
            print(f"  seed {seed_i}: {ss['passed']}/{ss['total']} passed, "
                  f"abs_err={ss['max_abs_err']:.2e}, rel_err={ss['max_rel_err']:.2e} -> {tag}")
            if not ss["all_pass"]:
                all_seeds_pass = False
                s["failures"].append(
                    f"seed{seed_i}: " + ("; ".join(ss["failures"]) or "correctness failure")
                )
            worst_abs_all = max(worst_abs_all, ss["max_abs_err"])
            worst_rel_all = max(worst_rel_all, ss["max_rel_err"])
            try:
                traces_seed.unlink()
            except OSError:
                pass
        print(f"  ────────────────────────────────────────────────────────────────")
        print(f"  MULTI-SEED RESULT        : {'PASS' if all_seeds_pass else 'FAIL'}")
        print(f"  worst abs / rel (all)    : {worst_abs_all:.2e} / {worst_rel_all:.2e}")
        s["max_abs_err"] = worst_abs_all
        s["max_rel_err"] = worst_rel_all
        if not all_seeds_pass:
            print(f"  *** KERNEL NOT ROBUST — fails on some seeds ***")
            s["all_pass"] = False

    # The gateway sandbox intentionally does not receive or return memory/.
    # Emit the full structured result so the local optimization session can
    # update memory/v<N>.json after a remote --no-memory run.
    print("[test_kernel] RESULT_JSON=" + json.dumps(s, ensure_ascii=False, sort_keys=True))

    if not args.no_memory:
        version = args.version or _infer_version(workspace)
        rec = _record_memory(workspace, version, s)
        print(f"[test_kernel] recorded -> {rec}")

    # On PASS, the current kernel is submittable — emit the ready-to-submit artifact now,
    # so every passing version has one without a separate finalize/re-validation step.
    if s["all_pass"]:
        sub = _write_submission(workspace)
        if sub:
            print(f"[test_kernel] ready-to-submit -> {sub}")

    # Non-zero exit signals a non-submittable version (some workload failed).
    return 0 if s["all_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
